### ISSUE TITLE
Payload du GET /wine

### ISSUE THREAD

**Issue by lks** [WineIsCool/wine-open-data#1]
Hello,

Il faudra que nous réfléchissons au retour de notre API concernant les objets liés à Wine (Region, Appellation, WineType).
L'idéal sera dans le retour de GET /wine pour les sous objets, d'avoir ce format :
...,
region: {id: 98, label: "Bourgogne"},
...,

En effet, ce type de retour, permettra au front de ne pas complexifier l'affichage.

Qu'en penses-tu ?

**Comment by yujloup** [comment]
oui je me suis dis la même chose.
Ca évitera de refaire un appel pour chaque sous-objet juste pour afficher le label.
